/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as donationRouterSol from './DonationRouter.sol/index.js';
export type { donationRouterSol };
import type * as testUsdtSol from './testUSDT.sol/index.js';
export type { testUsdtSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { DonationRouter } from './DonationRouter.sol/DonationRouter.js';
export { DonationRouter__factory } from './factories/DonationRouter.sol/DonationRouter__factory.js';
export type { TestUSDT } from './testUSDT.sol/TestUSDT.js';
export { TestUSDT__factory } from './factories/testUSDT.sol/TestUSDT__factory.js';