/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface DonationRouterInterface extends Interface {
    getFunction(nameOrSignature: "campaigns" | "donate" | "getCampaign" | "owner" | "renounceOwnership" | "setCampaign" | "transferOwnership" | "usdt"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCreated" | "CampaignUpdated" | "DonationReceived" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'donate', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCampaign', values: [BigNumberish, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdt', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdt', data: BytesLike): Result;
  }

  
    export namespace CampaignCreatedEvent {
      export type InputTuple = [campaignId: BigNumberish, recipient: AddressLike];
      export type OutputTuple = [campaignId: bigint, recipient: string];
      export interface OutputObject {campaignId: bigint, recipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignUpdatedEvent {
      export type InputTuple = [campaignId: BigNumberish, recipient: AddressLike, active: boolean];
      export type OutputTuple = [campaignId: bigint, recipient: string, active: boolean];
      export interface OutputObject {campaignId: bigint, recipient: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DonationReceivedEvent {
      export type InputTuple = [campaignId: BigNumberish, donor: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, donor: string, recipient: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, donor: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DonationRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): DonationRouter;
    waitForDeployment(): Promise<this>;

    interface: DonationRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, boolean] & {recipient: string, active: boolean }],
      'view'
    >
    

    
    donate: TypedContractMethod<
      [campaignId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [[string, boolean] & {recipient: string, active: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setCampaign: TypedContractMethod<
      [campaignId: BigNumberish, recipient: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, boolean] & {recipient: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'donate'): TypedContractMethod<
      [campaignId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [[string, boolean] & {recipient: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, recipient: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'CampaignUpdated'): TypedContractEvent<CampaignUpdatedEvent.InputTuple, CampaignUpdatedEvent.OutputTuple, CampaignUpdatedEvent.OutputObject>;
getEvent(key: 'DonationReceived'): TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'CampaignCreated(uint256,address)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'CampaignUpdated(uint256,address,bool)': TypedContractEvent<CampaignUpdatedEvent.InputTuple, CampaignUpdatedEvent.OutputTuple, CampaignUpdatedEvent.OutputObject>;
      CampaignUpdated: TypedContractEvent<CampaignUpdatedEvent.InputTuple, CampaignUpdatedEvent.OutputTuple, CampaignUpdatedEvent.OutputObject>;
    

      'DonationReceived(uint256,address,address,uint256)': TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
      DonationReceived: TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }