/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from './Counter.sol/index.js';
export * as donationRouterSol from './DonationRouter.sol/index.js';
export * as testUsdtSol from './testUSDT.sol/index.js';